server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_shop?currentSchema=task
    username: spring
    password: spring
  liquibase:
    change-log: classpath:db/changelog-master.yaml

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

